//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCLogistics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int PK_ItemID { get; set; }
        public Nullable<int> Weight { get; set; }
        public string SizeCategory { get; set; }
        public string Type { get; set; }
        public string InsuranceType { get; set; }
        public string RecordedDelivery { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
