//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCLogistics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Trackings = new HashSet<Tracking>();
        }
    
        public int PK_OrderID { get; set; }
        public int FK_ItemID { get; set; }
        public int FK_CustomerID { get; set; }
        public int FK_BranchAddressID { get; set; }
        public int FK_DeliveryAddressID { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Tracking> Trackings { get; set; }
        public virtual Item Item { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
    }
}
