//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCLogistics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcel
    {
        public string PK_ParcelID { get; set; }
        public string FK_CustomerID { get; set; }
        public string CustomerLastname { get; set; }
        public string FK_DeliveryAddressID { get; set; }
        public string CustomerTown { get; set; }
        public string CustomerPostcode { get; set; }
        public string CustomerTelephoneNumber { get; set; }
        public string CustomerEmail { get; set; }
        public string FK_OrderID { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public Nullable<System.DateTime> DateDispatched { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public string FK_BranchID { get; set; }
        public string BranchName { get; set; }
    }
}
