//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCLogistics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int PK_UserID { get; set; }
        public Nullable<int> FK_BillingAddressID { get; set; }
        public Nullable<int> FK_DeliveryAddressID { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string MobileNumber { get; set; }
        public string LandlineNumber { get; set; }
        public string EmailAddress { get; set; }
        public string SystemRole { get; set; }
        public string Password { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
